name: Report

on:
  repository_dispatch:
    types:
      - repository_edited

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      PAYLOAD: ${{ toJSON(github.event.client_payload }}
    steps:
      - name: Report
        # Do something with the payload
        run: |
          echo $PAYLOAD
