on:
  workflow_dispatch:
    inputs:
      changes:
        description: 'The detected changes'
        required: true
        type: Object
      repository:
        description: 'The repository'
        required: true
        type: Object
        
jobs:
  echo:
    runs-on: ubuntu-latest
    if:  ${{ inputs.changes.topics }} # Check if "topics" key is in changes
    steps:
      - name: Print repository name
        run: echo ${{ inputs.repository.name }}
        
      - name: Print topics
        run: echo ${{ inputs.repository.topics }}
