on:
  workflow_dispatch:
    inputs:
      repository_full_name:
        description: 'Full name of repository'
        required: true
        type: string
      flake_name:
        description: "Name of flake (repository name without symbols)"
        required: true
        type: string
      
        
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
     # - name: Print inputs
     #   run: echo ${{ toJson(inputs) }}
        
     # - name: Print event
     #   run: echo ${{ toJson(github.event) }}
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACTION }} 
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Register
        uses: workflow/nix-shell-action@v3.2.0
        with:
          script: nix registry add --registry ./flake-registry.json ${{ inputs.flake_name }} github:${{ inputs.repository_full_name }}
      - name: Cat registry
        run: cat ./flake-registry.json
      - name: Commit update
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Register new flake ${{ inputs.flake_name }}"
          git push
