on:
  workflow_dispatch:
    inputs:
      action:
        description: "The trigger action"
        required: true
        type: string
      changes:
        description: 'The detected changes'
        required: true
        type: object
      repository:
        description: 'The repository'
        required: true
        type: object
        
jobs:
  echo:
    if: ${{ inputs.action == 'edited' }}
    runs-on: ubuntu-latest
    # if:  ${{ inputs.changes.topics }} # Check if "topics" key is in changes
    steps:
      - name: Print inputs
        run: echo ${{ inputs }}
        
      - name: Print event
        run: echo ${{ github.event }}
        
      - name: Print repository name
        run: echo ${{ inputs.repository.name }}
        
      - name: Print topics
        run: echo ${{ inputs.repository.topics }}
