name: Webhook Actions trigger

on:
  repository_dispatch:
    types:
      - repository

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: print event
      run: echo ${{ toJson(github.event) }}
